#+PROPERTY: LOGGING nil

* org-make-toc
:PROPERTIES:
:TOC:      ignore
:END:

[[https://melpa.org/#/helm-org-rifle][file:https://melpa.org/packages/org-make-toc-badge.svg]] [[https://stable.melpa.org/#/helm-org-rifle][file:https://stable.melpa.org/packages/org-make-toc-badge.svg]]

This package makes it easy to have a customizable table of contents in Org files that can be updated manually, or automatically when the file is saved.  Links to headings are created compatible with GitHub's Org renderer.

* Contents                                                         :noexport:
:PROPERTIES:
:TOC:      this
:END:
  -  [[#installation][Installation]]
  -  [[#usage][Usage]]
  -  [[#changelog][Changelog]]
  -  [[#credits][Credits]]
  -  [[#development][Development]]
  -  [[#license][License]]

* Installation
:PROPERTIES:
:TOC:      0
:END:

** MELPA

If you installed from MELPA, you're done.

** Manual

  Install these required packages:

+  =dash=
+  =s=

  Then put this file in your load-path, and put this in your init file:

  #+BEGIN_SRC elisp
    (require 'org-make-toc)
  #+END_SRC

* Usage
:PROPERTIES:
:TOC:      0
:END:

1.  Make a heading in the Org file where you want the table of contents, and give it the Org property =TOC= with the value =this=.
2.  Run the command =org-make-toc=.

** Customization

The table of contents can be customized by setting the =TOC= property of headings:

+  Set to =ignore= to omit a heading from the TOC.
+  Set to =ignore-children= or =0= to omit a heading's child headings from the TOC.
+  Set to a number =N= to include child headings no more than =N= levels deep in the TOC.

** Automatically update on save

To automatically update a file's TOC when the file is saved, use the command =add-file-local-variable= to add =org-make-toc= to the Org file's =before-save-hook=.

** Example

See [[https://raw.githubusercontent.com/alphapapa/org-make-toc/master/README.org][this readme file]] for an example of the features described above.

* Changelog
:PROPERTIES:
:TOC:      0
:END:

** 0.1

Initial release.

* Credits

This package was inspired by Sergei Nosov's [[https://github.com/snosov1/toc-org][toc-org]] package.

* Development

Bug reports, feature requests, suggestions — /oh my/!

* License

GPLv3

# Local Variables:
# eval: (require 'org-make-toc)
# before-save-hook: (lambda nil (org-make-toc))
# org-export-with-properties: ()
# org-export-with-title: t
# End:

